feat : pemkey 수정

diff --git a/.github/workflows/deploy-server-with-compose.yml b/.github/workflows/deploy-server-with-compose.yml
--- a/.github/workflows/deploy-server-with-compose.yml
+++ b/.github/workflows/deploy-server-with-compose.yml
@@ -23,3 +23,19 @@ jobs:
 
       - name: push to dockerhub
         run: docker push rro0628/ordersystem:latest
+      
+      - name: ec2 ssh login and docker compose update
+        uses: appleboy/ssh-action@master
+        with:
+          host: ec2-54-66-145-232.ap-southeast-2.compute.amazonaws.com
+          username: ubuntu
+          key: ${{secrets.EC2_NEW_PEMKEY}}
+          script: |
+            if ! type docker > /dev/null ; then
+              sudo snap install docker || echo "docker install failed..."
+            fi
+            sudo docker login --username {{secrets.DOCKER_EMAIL}} --password ${{secrets.DOCKER_PASSWORD}}
+
+            sudo docker-compose pull && sudo docker-compose up -d
+          
+
